dependencies: virtualenv
  firebase_admin
  Authlib
  vertexai
  flask_cors

GOOGLE_FIREBASE_URL: "https://legalaid-402716-default-rtdb.firebaseio.com/"

GOOGLE_OAUTH_ENV:
  CLIENT_ID: ""
  CLIENT_SECRET: ""

GOOGLE_MAPS_API_KEY:
